import type jsPDF from 'jspdf';
import type { Product, ProductComputed, UserProfile } from '../types';
import { formatDisplayDate } from './deadline';

const PAGE_WIDTH = 612; // 8.5in @ 72dpi
const PAGE_HEIGHT = 792; // 11in @ 72dpi
const MARGIN = 54; // 0.75in
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function addWrapped(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

function drawPageChrome(doc: jsPDF, footerNote: string) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Topps Access Finder — an independent collector utility, not affiliated with Topps.', MARGIN, PAGE_HEIGHT - 30);
  doc.text(footerNote, MARGIN, PAGE_HEIGHT - 18);
}

/**
 * Draws one product's cover sheet onto the current page of `doc`, starting
 * near the top of the page. Caller is responsible for calling doc.addPage()
 * between products.
 */
export function drawEntryPage(
  doc: jsPDF,
  product: Product,
  computed: ProductComputed,
  profile: UserProfile,
  entryLabel?: string,
): void {
  let y = MARGIN;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(90, 100, 120);
  doc.text('TOPPS ACCESS FINDER — MAIL-IN SUBMISSION COVER SHEET', MARGIN, y);
  y += 14;
  doc.setDrawColor(200);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 22;

  if (entryLabel) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 63);
    doc.text(entryLabel, MARGIN, y);
    y += 16;
    doc.setFont('helvetica', 'bolditalic');
    doc.setFontSize(10);
    doc.setTextColor(180, 60, 20);
    doc.text('ONE PRODUCT PER ENVELOPE — DO NOT COMBINE WITH OTHER ENTRIES', MARGIN, y);
    y += 22;
  }

  if (product.isPlaceholder) {
    doc.setFillColor(255, 235, 235);
    doc.setDrawColor(220, 80, 80);
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 34, 3, 3, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(160, 30, 30);
    y = addWrapped(
      doc,
      'SAMPLE DATA — NOT VERIFIED AGAINST OFFICIAL TOPPS SOURCES. Do not mail this. Verify official rules, address, and deadline before submitting a real entry.',
      MARGIN + 8,
      y + 13,
      CONTENT_WIDTH - 16,
      11,
    );
    y += 14;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text('PRODUCT', MARGIN, y);
  y += 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(20, 28, 45);
  y = addWrapped(doc, product.exactEligibleProductName ?? product.productName, MARGIN, y, CONTENT_WIDTH, 16);
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text('ENTRY DEADLINE', MARGIN, y);
  y += 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(20, 28, 45);
  doc.text(formatDisplayDate(computed.entryDeadline), MARGIN, y);
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text('MAIL TO', MARGIN, y);
  y += 12;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(20, 28, 45);
  if (product.submissionAddress) {
    const addr = product.submissionAddress;
    const addressLines = [
      addr.name,
      addr.attnLine,
      addr.addressLine1,
      addr.addressLine2,
      `${addr.city}, ${addr.state} ${addr.zip}`,
      addr.country,
    ].filter((line): line is string => !!line);
    for (const line of addressLines) {
      y = addWrapped(doc, line, MARGIN, y, CONTENT_WIDTH, 14);
    }
  } else {
    doc.setTextColor(180, 60, 20);
    doc.text('Not yet verified — check the official rules before mailing.', MARGIN, y);
    y += 14;
  }
  y += 12;

  if (product.envelopeRequirements || product.handwrittenRequirements) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text('ENVELOPE / HANDWRITTEN REQUIREMENTS', MARGIN, y);
    y += 12;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(60, 70, 90);
    if (product.envelopeRequirements) {
      y = addWrapped(doc, product.envelopeRequirements, MARGIN, y, CONTENT_WIDTH, 12);
    }
    if (product.handwrittenRequirements) {
      y = addWrapped(doc, product.handwrittenRequirements, MARGIN, y, CONTENT_WIDTH, 12);
    }
    y += 10;
  }

  y += 6;
  doc.setDrawColor(210);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text('YOUR RETURN ADDRESS (for your own records)', MARGIN, y);
  y += 12;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(20, 28, 45);
  const userLines = [
    profile.fullName,
    profile.addressLine1,
    profile.addressLine2,
    `${profile.city}, ${profile.state} ${profile.zip}`,
    profile.country,
  ].filter((line): line is string => !!line);
  for (const line of userLines) {
    y = addWrapped(doc, line, MARGIN, y, CONTENT_WIDTH, 14);
  }
  y += 16;

  if (product.officialSubmissionFormUrl || product.officialRulesUrl) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text('OFFICIAL LINKS', MARGIN, y);
    y += 12;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(40, 90, 200);
    if (product.officialSubmissionFormUrl) {
      doc.textWithLink('Official submission form', MARGIN, y, { url: product.officialSubmissionFormUrl });
      y += 13;
    }
    if (product.officialRulesUrl) {
      doc.textWithLink('Official rules', MARGIN, y, { url: product.officialRulesUrl });
      y += 13;
    }
    y += 8;
  }

  doc.setFillColor(255, 249, 230);
  doc.setDrawColor(210, 170, 60);
  const noticeY = y;
  doc.roundedRect(MARGIN, noticeY, CONTENT_WIDTH, 30, 3, 3, 'FD');
  doc.setFont('helvetica', 'bolditalic');
  doc.setFontSize(8.5);
  doc.setTextColor(120, 90, 10);
  addWrapped(
    doc,
    'Do not alter official requirements. If Topps provides an official entry form, use it as-is — this cover sheet is a companion, not a replacement.',
    MARGIN + 8,
    noticeY + 12,
    CONTENT_WIDTH - 16,
    11,
  );

  drawPageChrome(doc, `Product ID: ${product.id}  |  Printed ${new Date().toLocaleDateString()}`);
}

export async function generateEntryPdf(product: Product, computed: ProductComputed, profile: UserProfile): Promise<jsPDF> {
  const { default: JsPDF } = await import('jspdf');
  const doc = new JsPDF({ unit: 'pt', format: 'letter' });
  drawEntryPage(doc, product, computed, profile);
  return doc;
}

export async function generatePrintAllPdf(
  items: Array<{ product: Product; computed: ProductComputed }>,
  profile: UserProfile,
): Promise<jsPDF> {
  const { default: JsPDF } = await import('jspdf');
  const doc = new JsPDF({ unit: 'pt', format: 'letter' });
  items.forEach((item, index) => {
    if (index > 0) doc.addPage();
    drawEntryPage(doc, item.product, item.computed, profile, `ENTRY ${index + 1} OF ${items.length}`);
  });
  return doc;
}

function safeFileName(name: string): string {
  return name.replace(/[^a-z0-9-_]+/gi, '-').toLowerCase();
}

export function downloadPdf(doc: jsPDF, fileName: string): void {
  doc.save(`${safeFileName(fileName)}.pdf`);
}

export function printPdf(doc: jsPDF): void {
  doc.autoPrint();
  const url = doc.output('bloburl');
  window.open(url, '_blank');
}
